project:
  title: "cv_typst"
  type: default
  output-dir: docs
# exclude files
  render:
    - "*.qmd"
    - "!Domanda_EUTALIA.qmd" # anonimo
    - "!CV_ita_long.qmd" # anonimo
    - "!letter*.qmd" # cazzi miei
    - "!*PH*.qmd" # occasionale

execute:
  freeze: auto

