---
format: 
  pdf:
    include-in-header:
      text: |
        \usepackage{xcolor}
        \usepackage[margin=1in]{geometry}
        \usepackage{fontspec}
        \setmainfont{Lato}[BoldFont={Lato Bold}]
        \pagestyle{empty}
        \fontsize{12}{15}\selectfont
sender:
  name: "Luisa M. Mimmi"
  title: "Data Scientist"
  email: "lmm76@georgetown.edu"
  phone: "+39-348-9528360"
  address: "Via Scarpa, 11"
  city: "Pavia"
  state: "PV"
  zip: "27100"
  website: "www.luisamimmi.org"


recipient: "Hiring Manager"
company: "Company Name"
job_role: "Data Scientist (remote)"
company_address:
  street: "123 Business Avenue"
  city: "San Francisco"
  state: "CA"
  zip: "94105"

date: today
date-format: "MMMM D, YYYY"

profile1: "development economist" 
profile2: "quantitative policy analyst"
profile3: "analytics consultant"

keyword1: "data analysis"
keyword2: "statistics and machine learning"
keyword3: "EU structural funds"
---
<!-- https://chatgpt.com/c/67bb0a1c-13f0-800f-aec8-fe6905991101 -->


<!-- ```{bash} -->
<!-- #| eval: false -->
<!-- #| echo: false -->

<!-- brew install --cask font-lato -->
<!-- fc-cache -f -v -->
<!-- fc-list | grep "Lato" -->
<!-- ``` -->
  
  
\begin{flushright}
\textbf{ {{< meta sender.name >}} } \\  % occhio a separare  { {{}}
{{< meta sender.email >}} \\
{{< meta sender.phone >}} \\
{{< meta sender.website >}} \\
{{< meta sender.address >}} \\
{{< meta sender.city >}}, {{< meta sender.state >}} {{< meta sender.zip >}}
\end{flushright}

\vspace{2em}

<!-- {{< meta recipient >}} -->
\begin{flushleft}
\textbf{ {{< meta company >}} } \\
{{< meta company_address.street >}} \\
{{< meta company_address.city >}}, {{< meta company_address.state >}} {{< meta company_address.zip >}}
\end{flushleft}


\vspace{2em}

\begin{flushright}
{{< meta sender.city >}}, {{< meta date >}}  
\end{flushright}

\vspace{2em}

**Subject**: Application to position of \textbf{ {{< meta job_role >}} } at \textbf{ {{< meta company >}} }

\vspace{2em}

Dear {{< meta recipient >}},  

<!-- Introduction -->
I am excited to apply for the {{< meta job_role >}} position at {{< meta company >}}. With a background as a {{< meta profile1 >}}, I bring extensive experience in {{< meta keyword1 >}}, {{< meta keyword2 >}}, and strategic decision-making through data.  

<!-- Me -->
With a background as a {{< meta profile1 >}}, I spent over a decade in research-focused roles at Multilateral Development Banks in Washington, DC, after earning my degree from Georgetown University in 2008. As a {{< meta profile2 >}}, I developed strong analytical and communication skills that have been instrumental in my work. Since returning to Italy in 2020, I have worked as a {{< meta profile3 >}}, advising public and private entities, research institutes, and nonprofits. 
My recent work includes supporting the Italian government in monitoring and financial reporting for the PNRR plan, which enhanced my expertise in {{< meta keyword3 >}}.  

<!-- Why you -->
{{< meta company >}}’s mission aligns with my passion for using data to drive strategic decision-making. Beyond technical competencies, I thrive in collaborative environments and have successfully led innovative projects from inception to completion. Communicating results effectively is another key strength, demonstrated by my extensive experience in research writing and presentations at conferences and seminars.  

<!-- Closing -->
I would welcome the opportunity to discuss how my background aligns with your team’s needs. Please feel free to reach out at your convenience.

Sincerely,  

\vspace{2em}

{{< meta sender.name >}} 
 
